---
title: "Pilot: MBR 4.0"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Pilot: MBR 4.0}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Install R package

```{r install, eval = FALSE}
remotes::install_github("kwb-r/kwb.pilot", 
                        upgrade = "always",
                        dependencies = TRUE)

```

## Define paths 

In `paths_list` you need set the environment variable ` Sys.getenv("MBR4.0_URL")` **only once** with `usethis::edit_r_environ()` as shown below:

```{r r_environment, eval = FALSE}
MBR4.0_URL = "url-to-download-pilot-plant-data"
```

Subsequently click **Save** and restart RStudio.

```{r paths_kwb, eval = TRUE}

paths_list <- list(
  url = Sys.getenv("MBR4.0_URL"),
  export_dir = tempdir(),
  tsv_file = "<export_dir>/mbr4.tsv"
  )

paths <- kwb.utils::resolve(paths_list)
```



## Import 

```{r import, eval = TRUE}
library(kwb.pilot)

mbr4_data_raw <- kwb.pilot::read_mbr4(url = paths$url, 
                                      target_path = paths$tsv_file)
str(mbr4_data_raw)

mbr4_data_tidy <- kwb.pilot::tidy_mbr4_data(mbr4_data = mbr4_data_raw)

str(mbr4_data_tidy)

```

## Aggregate

```{r aggregate, eval = TRUE}
mbr4_data_tidy_10min <- mbr4_data_tidy %>% kwb.pilot::group_datetime(by = 600)
mbr4_data_tidy_1hour <- mbr4_data_tidy %>% kwb.pilot::group_datetime(by = 3600)
```

## Export 

### CSV files 

```{r export_data, eval = FALSE}
kwb.pilot::export_data(mbr4_data_tidy, export_dir = paths$export_dir)
kwb.pilot::export_data(mbr4_data_tidy_10min, export_dir = paths$export_dir)
kwb.pilot::export_data(mbr4_data_tidy_1hour, export_dir = paths$export_dir)
```

### Interactive HTML plots

```{r plot_data, eval = FALSE}
kwb.pilot::plot_data(mbr4_data_tidy_10min, export_dir = paths$export_dir)
kwb.pilot::plot_data(mbr4_data_tidy_1hour, export_dir = paths$export_dir)
#kwb.pilot::plot_data(mbr4_data_tidy, export_dir = paths$export_dir)
```

