#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mrustl on 2021-02-26 14:17:35.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("calculate_operational_parameters_berlin_f() works", {
  f <- kwb.pilot:::calculate_operational_parameters_berlin_f

  expect_error(
    kwb.pilot:::calculate_operational_parameters_berlin_f()
    # Argument "df" fehlt (ohne Standardwert)
  )
})
