#
# This test file has been generated by kwb.test::create_test_files()
#

### Disable test which fails on Travis
# test_that("aggregate_export_fst_berlin_s() works", {
#
#   kwb.pilot:::aggregate_export_fst_berlin_s()
# })
#
