#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("plot_calculated_operational_timeseries() works", {
  expect_error(kwb.pilot:::plot_calculated_operational_timeseries())
})
