#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mrustl on 2022-06-01 19:12:25.633373.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("merge_and_export_fst() works", {

  expect_error(
    kwb.pilot:::merge_and_export_fst()
    # Your dataset needs at least one column.
  )

})

