#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mrustl on 2021-02-26 14:17:34.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("check_or_create_export_dir() works", {

  f <- kwb.pilot:::check_or_create_export_dir

  expect_error(
    f()
    # Argument "path" fehlt (ohne Standardwert)
  )

})
