#
# This test file has been generated by kwb.test::create_test_files()
#

### Disable test which fails on Travis
# test_that("get_monthly_data_from_calendarweeks() works", {
#
#   kwb.pilot:::get_monthly_data_from_calendarweeks()
# })
