#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("calculate_operational_parameters_berlin_t() works", {

  expect_error(kwb.pilot:::calculate_operational_parameters_berlin_t())
})

